blank_issues_enabled: false
contact_links:
- name: ğŸ’¬ Community Forum
  url: https://forums.bagisto.com
  about: This repository is only for reporting bugs or feature requests, if you need help please go to our community forum.
- name: â” Support Question
  url: https://bagisto.uvdesk.com/en/customer/create-ticket/
  about: This repository is only for reporting bugs or feature requests, please create a support ticket if you need any assistance from our team.  
